import type { ChangeEvent, ComponentType, Dispatch, RefObject, SetStateAction } from "react";
import type { BackgroundControls, ControlTab, FocusControls, GrabControls, LightingControls, MaterialControls, MeshQuality, MoodPreset, TransitionMode, WindControls, WindSoundControls } from "./config";

export type LocalControlProps = {
  controlsOpen: boolean;
  setControlsOpen: Dispatch<SetStateAction<boolean>>;
  settingsButtonRef: RefObject<HTMLButtonElement | null>;
  reset: () => void;
  moodEditorOpen: boolean;
  allMoods: MoodPreset[];
  activeMoodId: string | null;
  applyMood: (mood: MoodPreset) => void;
  removeCustomMood: (moodId: string) => void;
  setMoodEditorOpen: Dispatch<SetStateAction<boolean>>;
  setMoodNameDraft: Dispatch<SetStateAction<string>>;
  saveCurrentMood: (event: React.FormEvent<HTMLFormElement>) => void;
  moodNameDraft: string;
  activeControlTab: ControlTab;
  setActiveControlTab: Dispatch<SetStateAction<ControlTab>>;
  flagSize: number;
  setFlagSize: Dispatch<SetStateAction<number>>;
  wind: WindControls;
  updateWind: (key: keyof WindControls) => (value: number) => void;
  grabSettings: GrabControls;
  updateGrab: (key: keyof GrabControls) => (value: number) => void;
  windSoundEnabled: boolean;
  toggleWindSound: () => Promise<void>;
  windSound: WindSoundControls;
  updateWindSound: (key: keyof WindSoundControls, value: number) => void;
  clothSoundEnabled: boolean;
  toggleClothSound: () => Promise<void>;
  meshQuality: MeshQuality;
  setMeshQuality: Dispatch<SetStateAction<MeshQuality>>;
  tornMode: boolean;
  setTornMode: Dispatch<SetStateAction<boolean>>;
  color: string;
  setColor: Dispatch<SetStateAction<string>>;
  materialSettings: MaterialControls;
  setMaterialSettings: Dispatch<SetStateAction<MaterialControls>>;
  updateMaterial: (key: Exclude<keyof MaterialControls, "preset">) => (value: number) => void;
  activeDesign: string | null;
  premiereLightsEnabled: boolean;
  setPremiereLightsEnabled: Dispatch<SetStateAction<boolean>>;
  lighting: LightingControls;
  updateLighting: (key: Exclude<keyof LightingControls, "color">) => (value: number) => void;
  setLighting: Dispatch<SetStateAction<LightingControls>>;
  backgroundSettings: BackgroundControls;
  updateBackground: (key: keyof BackgroundControls, value: number) => void;
  focusControls: FocusControls;
  setFocusControls: Dispatch<SetStateAction<FocusControls>>;
  updateFocus: (key: Exclude<keyof FocusControls, "enabled">) => (value: number) => void;
  loadingPreview: boolean;
  setLoadingPreview: Dispatch<SetStateAction<boolean>>;
  transitionMode: TransitionMode;
  setTransitionMode: Dispatch<SetStateAction<TransitionMode>>;
  artworkName: string;
  handleArtwork: (event: ChangeEvent<HTMLInputElement>) => void;
  artworkScale: number;
  updateArtworkScale: (value: number) => void;
  togglePause: () => void;
  paused: boolean;
  fpsRef: RefObject<HTMLSpanElement | null>;
};

// Optional development editor; a clean checkout uses this empty component.
const LocalControls: ComponentType<LocalControlProps> = () => null;
export default LocalControls;
